[package]
name = "ffcli"
version = "0.4.4"
edition.workspace = true
license.workspace = true

[[bin]]
name = "fft"
path = "src/main.rs"

[dependencies]
ffcore = { path = "../ffcore" }
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
clap = { version = "4", features = ["derive", "env"] }
similar = "2"

[dev-dependencies]
tempfile = "3"
